version: '3.8'

services:
  selenium-app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DISPLAY=:99
      - DATABASE_URL=postgresql://postgres:11111@db:5432/tg_bot_egks
    entrypoint: ["sh", "-c", "poetry run alembic upgrade head && poetry run python start.py"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111
      POSTGRES_DB: tg_bot_egks
    ports:
      - "5432:5432"

  tg-bot:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:11111@db:5432/tg_bot_egks
    entrypoint: [ "sh", "-c", "poetry install && poetry run python start_tg_bot.py" ]



networks:
  default:
    driver: bridge
