# Используем базовый образ Python
FROM python:3.12

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы конфигурации Poetry
COPY pyproject.toml poetry.lock* /app/

# Устанавливаем Poetry и зависимости
RUN pip install poetry && poetry install --no-dev

# Копируем исходный код
COPY . /app

# Команда по умолчанию для запуска приложения
ENTRYPOINT ["poetry", "run", "python", "start_tg_bot.py"]
